#pragma once

#ifdef AUDIO_ENABLE
#define STARTUP_SONG SONG(PLANCK_SOUND)

#define MIDI_BASIC

#define ENCODER_RESOLUTION 4
#endif

#undef TAPPING_TERM
#define TAPPING_TERM 55

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "MqOVK/nldQG0"
#define LAYER_STATE_8BIT

