#include QMK_KEYBOARD_H
#ifdef AUDIO_ENABLE
#include "muse.h"
#endif
#include "eeprom.h"
#ifndef ZSA_SAFE_RANGE
#define ZSA_SAFE_RANGE SAFE_RANGE
#endif

enum custom_keycodes {
  RGB_SLD = ZSA_SAFE_RANGE,
};


enum tap_dance_codes {
  DANCE_0,
  DANCE_1,
  DANCE_2,
  DANCE_3,
  DANCE_4,
  DANCE_5,
  DANCE_6,
};

enum planck_layers {
  _BASE,
  _LOWER,
  _RAISE,
  _ADJUST,
};

#define LOWER MO(_LOWER)
#define RAISE MO(_RAISE)

#define DUAL_FUNC_0 LT(5, KC_D)

#define LOWER MO(_LOWER)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = { // Converted from _BASE
    { KC_TAB , KC_Q   , KC_W   , KC_E   , KC_R   , KC_T    }, // L0
    { TD(DANCE_0), KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO   }, // L1
    { KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO   }, // L2
    { KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO   }, // L3
    { KC_Y   , KC_U   , KC_I   , KC_O   , KC_P   , KC_ESCAPE }, // R0
    { KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO   }, // R1
    { KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO   }, // R2
    { KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO   }, // R3
  },
  [1] = { // Converted from _LOWER
    { KC_TILD, KC_1   , KC_2   , KC_3   , KC_4   , KC_5    }, // L0
    { KC_DELETE, KC_HOME, KC_UP  , KC_END , KC_PAGE_UP, KC_KP_ASTERISK }, // L1
    { KC_BSPC, KC_LEFT, KC_DOWN, KC_RIGHT, KC_PGDN, KC_KP_SLASH }, // L2
    { KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_BSLS, KC_LEFT_SHIFT, KC_TRANSPARENT }, // L3
    { KC_6   , KC_7   , KC_8   , KC_9   , KC_0   , KC_TRANSPARENT }, // R0
    { KC_KP_PLUS, KC_KP_4, KC_KP_5, KC_KP_6, KC_KP_EQUAL, KC_TRANSPARENT }, // R1
    { KC_KP_MINUS, KC_KP_1, KC_KP_2, KC_KP_3, KC_TRANSPARENT, KC_TRANSPARENT }, // R2
    { KC_NO  , KC_KP_COMMA, KC_KP_0, KC_KP_DOT, KC_MINUS, KC_EQUAL }, // R3
  },
  [2] = { // Converted from _RAISE
    { KC_TRANSPARENT, KC_F1  , KC_F2  , KC_F3  , KC_F4  , KC_F5   }, // L0
    { KC_TRANSPARENT, KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11  }, // L1
    { KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // L2
    { KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // L3
    { KC_F6  , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // R0
    { KC_F12 , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // R1
    { KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // R2
    { KC_NO  , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // R3
  },
  [3] = { // Converted from _ADJUST
    { KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // L0
    { KC_DELETE, KC_TRANSPARENT, QK_AUDIO_ON, QK_AUDIO_OFF, AU_TOGG, KC_TRANSPARENT }, // L1
    { KC_TRANSPARENT, KC_TRANSPARENT, QK_MUSIC_ON, QK_MUSIC_OFF, MU_TOGG, KC_TRANSPARENT }, // L2
    { KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // L3
    { KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // R0
    { KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, QK_BOOT }, // R1
    { KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // R2
    { KC_NO  , KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT }, // R3
  },
};