# Generated by oryx_to_olkb.py
# Planck Rev6 Vial Keymap Build Rules

# Vial support (dynamic remapping GUI)
VIAL_ENABLE = yes
DYNAMIC_KEYMAP_ENABLE = yes

# Tap dance support (required for TD() keycodes)
TAP_DANCE_ENABLE = yes

# Disable Vial's built-in tap dance to allow custom tap dances in keymap.c
VIAL_TAP_DANCE_ENABLE = no

# Audio support (Planck Rev6 has speaker/buzzer)
AUDIO_ENABLE = yes

# Music mode support (for encoder and audio features)
MUSIC_ENABLE = yes

# Link-Time Optimization (Disabled to prevent type mismatch errors with Vial)
LTO_ENABLE = no

# Introspection fix (Disabled to prevent conflicts with Vial's internal definitions)
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
