# Generated by oryx_to_olkb.py
# Planck Rev6 Vial Keymap Build Rules

# Vial support (dynamic remapping GUI)
VIAL_ENABLE = yes

# Tap dance support (required for TD() keycodes)
TAP_DANCE_ENABLE = yes

# Disable Vial's built-in tap dance (using QMK's native implementation)
VIAL_TAP_DANCE_ENABLE = no

# Audio support (Planck Rev6 has speaker/buzzer)
AUDIO_ENABLE = yes

# Music mode support (for encoder and audio features)
MUSIC_ENABLE = yes

# Link-Time Optimization (reduces firmware size)
LTO_ENABLE = yes

# Introspection fix
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
